Traceback (most recent call last):
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\anaconda3\envs\BookBuilder\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
def generate_test_case(setup, N, seed = 0, phi1=None, phi2=None,psi1=None,psi2=None):
    if setup == 'random_binary':
        np.random.seed(seed)
        s1 = np.random.normal(450,150, N)
        A1 = np.random.binomial(1,np.exp(phi1[0]+phi1[1]*s1)/(1+np.exp(phi1[0]+phi1[1]*s1)),size = N)
        s2 = np.random.normal(1.25*s1,60, N)
        A2 = np.random.binomial(1,np.exp(phi2[0]+phi2[1]*s2)/(1+np.exp(phi2[0]+phi2[1]*s2)),size = N)
        A = {}
        A[0] = A1
        A[1] = A2
        mu1 = (psi1[0]+psi1[1]*s1)*((psi1[0]+psi1[1]*s1 >0).astype(int)-A1)
        mu2 = (psi2[0]+psi2[1]*s2)*((psi2[0]+psi2[1]*s2 >0).astype(int)-A2)
        Y_opt = np.random.normal(400+1.6*s1,60)
        Y = Y_opt - mu1 - mu2
        opt_true = {}
        opt_true[0] = (psi1[0]+psi1[1]*s1 >0).astype(int)
        opt_true[1] = (psi2[0]+psi2[1]*s2 >0).astype(int)
        X = np.hstack([np.ones(N)[:, np.newaxis], s1[:, np.newaxis], A1[:, np.newaxis], (s1*A1)[:, np.newaxis], s2[:, np.newaxis]])
        
        instance = {
            'X' : X, 
            'A' : A, 
            'Y' : Y, 
            'optimal_A' : opt_true, 
            'optimal_V' : np.mean(Y_opt),
            'XAY' : [X, A, Y]
        }
        return instance
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_28252\3170494263.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mdef[0m [0mgenerate_test_case[0m[1;33m([0m[0msetup[0m[1;33m,[0m [0mN[0m[1;33m,[0m [0mseed[0m [1;33m=[0m [1;36m0[0m[1;33m,[0m [0mphi1[0m[1;33m=[0m[1;32mNone[0m[1;33m,[0m [0mphi2[0m[1;33m=[0m[1;32mNone[0m[1;33m,[0m[0mpsi1[0m[1;33m=[0m[1;32mNone[0m[1;33m,[0m[0mpsi2[0m[1;33m=[0m[1;32mNone[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m     [1;32mif[0m [0msetup[0m [1;33m==[0m [1;34m'random_binary'[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m         [0mnp[0m[1;33m.[0m[0mrandom[0m[1;33m.[0m[0mseed[0m[1;33m([0m[0mseed[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m         [0ms1[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mrandom[0m[1;33m.[0m[0mnormal[0m[1;33m([0m[1;36m450[0m[1;33m,[0m[1;36m150[0m[1;33m,[0m [0mN[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'

