Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "D:\Anaconda\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\Anaconda\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\Anaconda\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "D:\Anaconda\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Anaconda\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "D:\Anaconda\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "D:\Anaconda\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# After we publish the pack age, we can directly import it
# TODO: explore more efficient way
# we can hide this cell later
import os
os.getcwd()
os.chdir('..')
os.chdir('../CausalDM')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_17852/2982377520.py[0m in [0;36m<module>[1;34m[0m
[0;32m      5[0m [0mos[0m[1;33m.[0m[0mgetcwd[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [0mos[0m[1;33m.[0m[0mchdir[0m[1;33m([0m[1;34m'..'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 7[1;33m [0mos[0m[1;33m.[0m[0mchdir[0m[1;33m([0m[1;34m'../CausalDM'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mFileNotFoundError[0m: [WinError 2] 系统找不到指定的文件。: '../CausalDM'
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: '../CausalDM'

