Traceback (most recent call last):
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\anaconda3\envs\BookBuilder\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\anaconda3\envs\BookBuilder\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# After we publish the package, we can directly import it
# TODO: explore more efficient way
# we can hide this cell later
import os
os.getcwd()
os.chdir('..')
os.chdir('../CausalDM')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_77468\2987427551.py[0m in [0;36m<module>[1;34m[0m
[0;32m      5[0m [0mos[0m[1;33m.[0m[0mgetcwd[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [0mos[0m[1;33m.[0m[0mchdir[0m[1;33m([0m[1;34m'..'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 7[1;33m [0mos[0m[1;33m.[0m[0mchdir[0m[1;33m([0m[1;34m'../CausalDM'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mFileNotFoundError[0m: [WinError 2] Á≥ªÁªüÊâæ‰∏çÂà∞ÊåáÂÆöÁöÑÊñá‰ª∂„ÄÇ: '../CausalDM'
FileNotFoundError: [WinError 2] Á≥ªÁªüÊâæ‰∏çÂà∞ÊåáÂÆöÁöÑÊñá‰ª∂„ÄÇ: '../CausalDM'

