Traceback (most recent call last):
  File "/Users/wrunzhe/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/wrunzhe/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wrunzhe/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wrunzhe/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wrunzhe/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/wrunzhe/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/wrunzhe/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/wrunzhe/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
os.getcwd()
os.chdir('D:/Github/CausalDM')
# import learner
from causaldm._util_causaldm import *
from scipy.linalg import block_diag
class Single_Gaussian_Env():
    @autoargs()
    def __init__(self, true_model, sigma, seed = 42, with_intercept = True, logged_dat = False):
        self.setting = locals()
        self.setting['self'] = None
        self.seed = seed
        np.random.seed(self.seed)
        
        self.true_model = true_model
        self.sigma = sigma
        
        if logged_dat:
            self.get_logged_dat()
            
        
    def get_Phi(self):
        """ consider the simple case now 
        [K, p]
        """
        occup = np.random.multinomial(1, [1/5, 1/5, 1/5, 1/5, 1/5], size=1)
        gender = np.random.binomial(1, 1/2, size=1)
        age = np.random.randint(low=20, high=60, size = 1)
        user_info = age.tolist()+gender.tolist()+occup.tolist()[0][:-1]
        if self.with_intercept:
            user_info = [1] + user_info
        self.Phi = block_diag(*([np.array(user_info)] * 5))   
        return self.Phi
    
    def get_reward(self, a):
        self.r_mean = self.Phi.dot(self.true_model)
        self.r = self.r_mean
        return self.r[a] + abs(np.random.randn(1)[0])*self.sigma
    
    def optimal_action_reward(self):
        a = np.argmax(self.r)
        return a
    
    def get_logged_dat(self):
        true_model = self.true_model.reshape((5,-1))
        occup = np.random.multinomial(1, [2/5, 3/5, 0, 0, 0], size=100)
        gender = np.random.binomial(1, 1/20, size=100).reshape(-1,1)
        age = np.random.randint(low=20, high=25, size = 100).reshape(-1,1)
        rec_genre = np.random.randint(low=0, high=5, size = 100).reshape(-1,1)
        user_info = pd.DataFrame(np.concatenate((age, gender, occup, rec_genre), axis=1))
        user_info.columns = ['age', 'gender', 'educator', 'student', 'executive', 'technician', 'others','rec_genre']
        user_info['reward'] = user_info.apply(lambda row : np.dot(true_model[row['rec_genre']],
                                                          np.array([1]+row.iloc[:-2].tolist()))+
                                              self.sigma*abs(np.random.randn(1)[0]), axis = 1)
        self.user_info = user_info
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[1;32m      2[0m os[38;5;241m.[39mgetcwd()
[0;32m----> 3[0m os[38;5;241m.[39mchdir([38;5;124m'[39m[38;5;124mD:/Github/CausalDM[39m[38;5;124m'[39m)
[1;32m      4[0m [38;5;66;03m# import learner[39;00m
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcausaldm[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_util_causaldm[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'D:/Github/CausalDM'
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Github/CausalDM'

