Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load the data
import numpy as np
import pandas as pd
from causaldm.learners.CEL.Panel import _env_getdata_Panel
data_employment = _env_getdata_Panel.get_employment_CEL()
data_employment.head()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m----> 4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcausaldm[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlearners[39;00m[38;5;21;01m.[39;00m[38;5;21;01mCEL[39;00m[38;5;21;01m.[39;00m[38;5;21;01mPanel[39;00m [38;5;28;01mimport[39;00m _env_getdata_Panel
[0;32m      5[0m data_employment [38;5;241m=[39m _env_getdata_Panel[38;5;241m.[39mget_employment_CEL()
[0;32m      6[0m data_employment[38;5;241m.[39mhead()

[1;31mImportError[0m: cannot import name '_env_getdata_Panel' from 'causaldm.learners.CEL.Panel' (D:\anaconda3\lib\site-packages\causaldm\learners\CEL\Panel\__init__.py)
ImportError: cannot import name '_env_getdata_Panel' from 'causaldm.learners.CEL.Panel' (D:\anaconda3\lib\site-packages\causaldm\learners\CEL\Panel\__init__.py)

