Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# The code is available at https://github.com/claudiashi57/dragonnet
# import related packages
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt;
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from causaldm.learners.CEL.Single_Stage import _env_getdata_CEL
from causaldm.learners.CEL.Single_Stage.Dragonnet import *
import warnings
warnings.filterwarnings('ignore')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 8>[1;34m()[0m
[0;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mensemble[39;00m [38;5;28;01mimport[39;00m GradientBoostingRegressor
[0;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlinear_model[39;00m [38;5;28;01mimport[39;00m LinearRegression
[1;32m----> 8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcausaldm[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlearners[39;00m[38;5;21;01m.[39;00m[38;5;21;01mCEL[39;00m[38;5;21;01m.[39;00m[38;5;21;01mSingle_Stage[39;00m [38;5;28;01mimport[39;00m _env_getdata_CEL
[0;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcausaldm[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlearners[39;00m[38;5;21;01m.[39;00m[38;5;21;01mCEL[39;00m[38;5;21;01m.[39;00m[38;5;21;01mSingle_Stage[39;00m[38;5;21;01m.[39;00m[38;5;21;01mDragonnet[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mwarnings[39;00m

[1;31mImportError[0m: cannot import name '_env_getdata_CEL' from 'causaldm.learners.CEL.Single_Stage' (D:\anaconda3\lib\site-packages\causaldm\learners\CEL\Single_Stage\__init__.py)
ImportError: cannot import name '_env_getdata_CEL' from 'causaldm.learners.CEL.Single_Stage' (D:\anaconda3\lib\site-packages\causaldm\learners\CEL\Single_Stage\__init__.py)

